import fs from "node:fs";

const publicKey = process.env.TAURI_UPDATER_PUBLIC_KEY?.trim();
if (!publicKey || !process.env.TAURI_SIGNING_PRIVATE_KEY?.trim()) {
  throw new Error("Configure TAURI_UPDATER_PUBLIC_KEY (repository variable) and TAURI_SIGNING_PRIVATE_KEY (repository secret) before publishing.");
}
const decoded = Buffer.from(publicKey, "base64").toString("utf8");
if (!decoded.startsWith("untrusted comment:") || !decoded.trim().split("\n")[1]) {
  throw new Error("TAURI_UPDATER_PUBLIC_KEY must contain the public key generated by tauri signer generate.");
}
const path = "src-tauri/tauri.conf.json";
const config = JSON.parse(fs.readFileSync(path, "utf8"));
config.plugins.updater.pubkey = publicKey;
fs.writeFileSync(path, JSON.stringify(config, null, 2) + "\n");
